# Generated by Django 2.0.6 on 2018-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20180624_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(default='some@some.com', max_length=254),
        ),
    ]
