# Generated by Django 2.0.6 on 2018-06-26 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20180626_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='number_tables',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
