# Generated by Django 2.0.6 on 2018-06-26 15:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20180626_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(10, 0)), django.core.validators.MaxValueValidator(datetime.time(20, 0))]),
        ),
    ]
